### ISSUE TITLE
including item list rather than copy/paste

### ISSUE THREAD

**Issue by arkanic** [MindustryGame/wiki#1]
could you include the items list with a bit of code rather than copy/pasting it into every page?
something like this:
```html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js">
$(
function() {
$("#includeContent").load("itembar.htm");
});
</script>
</head>
<body>
<p>i is p element</p>
<div id="includeContent"></div>
</body>
</html>
```
it may be useful if new items are added, as it saves completely re-writing every file.
i made an issue bc i am nobody to tamper with code like this

**Comment by Anuken** [comment]
Which items list are you referring to?

**Comment by arkanic** [comment]
@anuken the floated index on the left, i probably couldve phrased myself better

**Comment by Anuken** [comment]
![Screenshot from 2019-06-10 18-47-47](https://user-images.githubusercontent.com/10100000/59231895-43d44300-8bb0-11e9-8fc9-637c64de8c4a.png)

Do you mean this?
I don't make any of it myself, it's all autogenerated every wiki update.

**Comment by arkanic** [comment]
@Anuken oh okay, i didn't know that
thanks
