### ISSUE TITLE
modding section

### ISSUE THREAD

**Issue by NACH0CHEE5E** [MindustryGame/wiki#10]
so i was looking into the modding section of the game, and decided to mess around and have a look, ive made a item with a minable ore, and while looking at it some things just dont make sense like the cost flag, if there somewhere where i can read up on it and then i might do some wiki page stuff

**Comment by Luxray5474** [comment]
I've made a cost section on there before, but I don't know if that's up to date. 

> Cost is how much time an item adds to the time it takes to build a block that uses it. One cost = one tick added to build time.

**Comment by NACH0CHEE5E** [comment]
oh
thanks
