### ISSUE TITLE
Should we make a spreadsheet (google docs) that shows the status of each of the manually written articles?

### ISSUE THREAD

**Issue by Luxray5474** [MindustryGame/wiki#11]
Just a suggestion as we had one before Anuke automated the creation of wiki pages. A few of our manually written pages are not up to date, and some are. However that might only complicate things. And if we have that, each page should have their own status. Any ideas?

**Comment by Anuken** [comment]
Do you have a link to the old spreadsheet or at least a picture of what it looked like? I'm not sure if that kind of format is the best way to track progress.

**Comment by Luxray5474** [comment]
I agree with you on that last part, we should make some sort of CI thing that updates a page with a table of all other pages every deployment.

Old spreadsheet: https://docs.google.com/spreadsheets/d/1wIRdj09dGPf28hX6y-YM_uP2Xp78T11raeDPbm21Ee8/edit?usp=sharing
