### ISSUE TITLE
"Types" is no longer as useful as it was

### ISSUE THREAD

**Issue by rylid-umil** [MindustryGame/wiki#111]
https://mindustrygame.github.io/wiki/modding/5-types/
i noticed this back in 2021/2022, types no longer includes helpful stuff like types, units, bullets weapons items etc. do you know why?

**Comment by Anuken** [comment]
The wiki is a bit of a mess now; the types were moved to e.g. https://mindustrygame.github.io/wiki/Modding%20Classes/Ability/ for easier linking, but there's no information about that subsection yet.
