### ISSUE TITLE
My mod is not working

### ISSUE THREAD

**Issue by ZalypaKonya** [MindustryGame/wiki#124]
I'm new to modding and I'm trying to increase the health of a 575 turbine condenser to 600 with mods, but it doesn't work when I log into the game.

//production
let TurbineCondenser = extend(block, "Turbine-Condenser", {
    size: 3,
    health: 600,
    requirements: ItemStack.with(Items.Beryllium, 60),
    buildCostMultiplier: 1,
    buildVisibility: BuildVisibility.shown,
    research: { parent: Blocks.TurbineCondenser },
    localizedName: "Turbine Condenser",
    category: Category.production,
    description: "Generate energy."
})
![2024-12-12_19-09-51](https://github.com/user-attachments/assets/2ee6693d-dcc9-4f9e-92f5-24723614950f)

![2024-12-12_19-10-23](https://github.com/user-attachments/assets/099214e5-9d31-421d-96bc-e836d26e4618)
![2024-12-12_19-11-26](https://github.com/user-attachments/assets/cfded9ed-d3fe-411a-bc2f-84fff14f593a)

**Comment by Anuken** [comment]
This is the wrong place to ask for modding help, check `#json` or `#scripting` in the Discord.
