### ISSUE TITLE
Adding wave reached requirements to zone infor

### ISSUE THREAD

**Issue by schumannd** [MindustryGame/wiki#13]
I found myself often in the situation where I have forgotten which wave I needed to reach to unlock the next zone. There is no ingame way to check this, and googling brings me to this wiki which frustratingly does not contain this info. If it si wanted, I will open a PR today that adds this info.

**Comment by Luxray5474** [comment]
I would not advise directly editing those files as they are automatically generated by [Anuke's Wikigen](https://github.com/Anuken/Mindustry-Wiki-Generator), and your changes will be erased the next release. I suggest starting a PR over there which makes the bot include that information in the content that it generates.

**Comment by macks2008** [comment]
huh, good thing I saw this because I was considering opening a PR for the exact same thing. Did you ever end up opening a PR with Anuken like Luxray suggested, @schumannd? Because I see the missing information is still missing and I'd like to contribute one way or the other.

**Comment by Anuken** [comment]
The entire zone system is being reworked/removed, so it's best to wait.
