### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by zeratulayuris** [MindustryGame/wiki#15]
Some thoughts on wiki navigation:

- make categories folded by default - it annoys to scroll all the way down to some entries.

- when viewing entry add an anchor to it's link on navbar and unfold it's category - same reason as above, annoyed to scroll to view entries from same category.

- make entry text in navbar span two lines so it's aligned with entry icon. Below is a screenshot with two misaligned entries:
![image](https://user-images.githubusercontent.com/9881249/68083052-0796cd00-fe46-11e9-9580-be79842de910.png)

**Comment by Arkanic** [comment]
i would do this, but the stylesheet makes no sense
theres stuff missing from it and i don't know how to edit the external theme

oh no

**Comment by Luxray5474** [comment]
jinja, templates, and black magic

**Comment by Anuken** [comment]
I've been wanting to implement these things for a while, but some searching a while ago did not give me any meaningful solutions.

**Comment by Luxray5474** [comment]
Closed because of recent pull request solving the issue.

**Comment by Anuken** [comment]
Not entirely. I tried to fix the scrolling, but all that happened was the return of the prev/next buttons. I'll look into this when I get home.
