### ISSUE TITLE
Auto-generated icons for turret ammo are broken

### ISSUE THREAD

**Issue by Ajedi32** [MindustryGame/wiki#24]
Example: https://mindustrygame.github.io/wiki/blocks/turret/ripple/

It seems like any ammo type which isn't directly mineable uses a broken image. (So ammo types like Copper and Lead display fine, but not Graphite, Pyratite, etc.)

Since that text is all auto-generated and (AFAIK) the source code for the script that does that isn't public, I'm unable to fix the problem myself.

**Comment by Anuken** [comment]
Fixed. [The generator repo _is_ public.](https://github.com/Anuken/Mindustry-Wiki-Generator)

**Comment by Ajedi32** [comment]
Ah I see, it's under your namespace. Good to know. 👍
