### ISSUE TITLE
does anyone know where the full stylesheet is?

### ISSUE THREAD

**Issue by Arkanic** [MindustryGame/wiki#4]
does anyone know if there is another stylesheet? i've found the style.css but it doesn't contain all of the css code.

I was trying to add some fade-opacity on hover effects to the sidebar

D:

**Comment by Anuken** [comment]
we may never know

**Comment by Luxray5474** [comment]
Some of the styling is done through CSS and some through that template in `custom_theme/`. What effect are you specifically trying to create?

**Comment by Arkanic** [comment]
@Anuken 
yes
