### ISSUE TITLE
Add ranking information to wiki

### ISSUE THREAD

**Issue by BobSaidHi** [MindustryGame/wiki#43]
The other day, I was wondering how the ranking system worked (after a core launch), but couldn't find any docs (I was finally pointed to [Stats.java#L102](https://github.com/Anuken/Mindustry/blob/61d9fd3d726f7744c6d42db244f3a18ac2c3f8ca/core/src/mindustry/game/Stats.java#L102) ).  If this is can be added manually, I could add it, but I'm not sure which wiki page would be best.

**Comment by Anuken** [comment]
This isn't a very good time to document the ranking system, as some of the information it relied upon is no longer available in 6.0.
