### ISSUE TITLE
nonexistent descriptions

### ISSUE THREAD

**Issue by Arkanic** [MindustryGame/wiki#5]
I've noticed a lot of "Unknown... "in the descriptions of objects in the wiki, should i just edit directly from the Mindustry repo (seeing as descriptions are imported from there) or shoud I edit them here?

**Comment by Anuken** [comment]
Make a list of the missing descriptions and I'll add them to Mindustry next update. The pages should auto-update after the release. Editing them would be pointless, as the part with the description is automatically generated.

**Comment by Arkanic** [comment]
@Anuken i've finished the 4 missing enemy names
```
- reaper
- lich
- chaos-array
- eradicator
```

https://github.com/Anuken/Mindustry/pull/1042

probably a bit late but i was doing other stuff

**Comment by Anuken** [comment]
As mentioned in the issue, I'll add my own descriptions eventually (once some lore is set up). For now, they will remain unknown.
