### ISSUE TITLE
Problem with maps added by mod

### ISSUE THREAD

**Issue by NJaSnow** [MindustryGame/wiki#53]
Hi, I'm having a problem when I change the loadout and the requirements on script. The game just ignore my changes and it don't release the waves on campaign. Could you help me to find out what is going on?
![2020-09-26 (2)](https://user-images.githubusercontent.com/67970859/94354035-7d52eb00-004d-11eb-96fd-9d3bce92cfba.png)

![2020-09-26](https://user-images.githubusercontent.com/67970859/94353893-5e078e00-004c-11eb-8981-6485eb501903.png)
![2020-09-26 (1)](https://user-images.githubusercontent.com/67970859/94353895-5fd15180-004c-11eb-8eb8-a60632027fe0.png)

**Comment by Anuken** [comment]
This has nothing to do with the wiki, and campaign maps of that form are no longer possible in V6.
