### ISSUE TITLE
Clicking the pencil to edit a wiki page redirects to 404

### ISSUE THREAD

**Issue by sudobeans** [MindustryGame/wiki#65]
When I click on the pencil icon on a page, it doesn't send me to the right place to edit it. In this example, clicking the pencil sends me to https://github.com/MindustryGame/wiki/edit/master/docs/blocks/168-steam-generator.md . This produces a 404 error. Instead, it should send me to https://github.com/MindustryGame/wiki/blob/gh-pages/blocks/168-steam-generator/index.html or something like that.
![screenshot](https://i.imgur.com/hEHR3Hr.jpg)

**Comment by Anuken** [comment]
Those pages don't exist in the wiki, so you can't edit them. They're autogenerated.
