### ISSUE TITLE
Launch pad and large launch pad missing

### ISSUE THREAD

**Issue by RichardRobertson** [MindustryGame/wiki#7]
The launch pad and large launch pad are missing from blocks/effects. You can see material pages linking to them as "Used to build" where they have an icon but no destination pages.

Are these being missed by the auto generator?

**Comment by Anuken** [comment]
Fixed.

**Comment by Evanevoyo** [comment]
@Anuken please add an option to enable legacy launch pads I really want them back sometimes. i hope u actually do this in the next beta version
