### ISSUE TITLE
Basic / Tier 1 units should list construction costs (page generator)

### ISSUE THREAD

**Issue by riking** [MindustryGame/wiki#73]
What it should look like:

 - Dagger: [silicon] 10, [lead] 10
 - Crawler: [silicon] 10, [coal] 20
 - Nova: [silicon] 30, [lead] 20, [titanium] 20
 - Flare: [silicon] 15
 - Mono: [silicon] 30, [lead] 15
 - Risso: [silicon] 20, [metaglass] 30

**Comment by notMEEPoffaith** [comment]
yes

**Comment by anka-213** [comment]
The same thing should probably be done with the in-game info viewer (e.g. in the research tree). The only way I could find in-game for figuring out what a unit costs is to actually produce it.

**Comment by Dan-Gamin** [comment]
The number of times I went into sandbox mode only to check how much a unit costs... We need this...

**Comment by Anuken** [comment]
Will be done next update, see https://github.com/MindustryGame/wiki-generator/issues/7
