### ISSUE TITLE
Rainstorm is used as an example

### ISSUE THREAD

**Issue by BlueWolf3682** [MindustryGame/wiki#85]
If you scroll through the modding types, you will notice that LaserTurret uses my Rainstorm turret as an example.
Rainstorm is 1,129 lines long.
...maybe make it not post any files above a certain size?

![Screenshot_20210926-164835](https://user-images.githubusercontent.com/61173114/134826958-c2427017-7617-4cb8-b2d1-e6e4fc81a4ad.png)

**Comment by Anuken** [comment]
> above a certain size?

What size would that be?

**Comment by BlueWolf3682** [comment]
![Screenshot_20210928-084726](https://user-images.githubusercontent.com/61173114/135110901-d5da8755-5a9b-4532-b434-18ff1d147af1.png)

I'd say limit the file size to below 3 kilobytes - usually anything larger is a massively worked on file.

**Comment by Anuken** [comment]
(fixed)
