### ISSUE TITLE
Update description of overdrive dome/projector to include that it increases speed of turrets

### ISSUE THREAD

**Issue by GaretWebster** [MindustryGame/wiki#94]
It's not immediately obvious.

**Comment by GaretWebster** [comment]
Also might be worth having:
Status to indicate something is working at a boosted rate. Maybe a blue light instead of a green one?

I also think statuses should be on by default, it really helps players diagnose potential issues with buildings and early on it really helps to know when you get something working properly for the first time.

**Comment by Anuken** [comment]
This isn't related to the wiki itself, it just scrapes descriptions from the game. See the [game suggestions repo.](https://github.com/Anuken/Mindustry-Suggestions)
