### ISSUE TITLE
My not working Turrets 

### ISSUE THREAD

**Issue by 040404040404** [MindustryGame/wiki#97]
https://www.mediafire.com/file/b2g9l2gk7in8b1g/Turrets.zip/file

Pls fix them. I'm not good at coding.

**Comment by MEEPofFaith** [comment]
this has nothing to do with the wiki, why are you submitting an issue on it

**Comment by SMOLKEYS** [comment]
1. sus name, very young account
2. why here, go to the mindustry discord
3. contrasting 2, fix it yourself 😎

**Comment by PalmTre** [comment]
ask the discord server instead lmao

**Comment by bendnuts** [comment]
wtf
